export enum SubIdAggregatorQueueName {
  ACCOUNT_AGGREGATION_FLOW = 'ACCOUNT_AGGREGATION_FLOW',
  DATASOURCE_HANDLING = 'DATASOURCE_HANDLING',
}

export enum SubIdAggregatorJobName {
  REFRESH_TX_HISTORY_FOR_ACCOUNT = 'REFRESH_TX_HISTORY_FOR_ACCOUNT',
  COLLECT_EVENT_DATA = 'COLLECT_EVENT_DATA',
}

export enum QueueJobStatus {
  ACTIVE = 'ACTIVE',
  WAITING = 'WAITING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}