export enum SubIdAggregatorQueueName {
  ACCOUNT_AGGREGATION_FLOW = 'ACCOUNT_AGGREGATION_FLOW',
  DATASOURCE_HANDLING = 'DATASOURCE_HANDLING',
  DATASOURCE_CHUNKS_PARALLEL_HANDLING = 'DATASOURCE_CHUNKS_PARALLEL_HANDLING',
}

export enum SubIdAggregatorJobName {
  REFRESH_TX_HISTORY_FOR_ACCOUNT_ON_DEMAND = 'REFRESH_TX_HISTORY_FOR_ACCOUNT_ON_DEMAND',
  REFRESH_TX_HISTORY_FOR_ACCOUNT_SCHEDULED = 'REFRESH_TX_HISTORY_FOR_ACCOUNT_SCHEDULED',
  COLLECT_EVENT_DATA = 'COLLECT_EVENT_DATA',
}

export enum QueueJobStatus {
  ACTIVE = 'ACTIVE',
  WAITING = 'WAITING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
